#!/bin/sh
set -eu

# Export a pip-friendly development requirements file as an additive layer
# over runtime requirements.
#
# Source of truth for dev dependencies:
# [project.optional-dependencies].dev in pyproject.toml

OUT_FILE="${1:-requirements-dev.txt}"

{
  echo "# This file is autogenerated from pyproject.toml ([project.optional-dependencies].dev)."
  echo "# Install runtime only: pip install -r requirements.txt"
  echo "# Install development: pip install -r ${OUT_FILE}"
  echo "-r requirements.txt"

  awk '
    BEGIN { in_optional=0; in_dev=0 }
    /^\[project\.optional-dependencies\]/ { in_optional=1; next }
    in_optional && /^\[/ && $0 !~ /^\[project\.optional-dependencies\]/ { in_optional=0 }

    in_optional && /^dev[[:space:]]*=[[:space:]]*\[/ { in_dev=1; next }
    in_dev && /^\][[:space:]]*$/ { in_dev=0; exit }

    in_dev {
      line=$0
      sub(/^[[:space:]]*"/, "", line)
      sub(/",?[[:space:]]*$/, "", line)
      if (length(line) > 0) print line
    }
  ' pyproject.toml
} > "$OUT_FILE"
